spring:
  application:
    name: mall-search
  profiles:
    active: dev #默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: smart.northsea.com:9200

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



